image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

stages:
- build
- test-pack
- deploy

variables:
  CONFIGURATION: Release

cache:
  key: "$CI_PIPELINE_ID"

build:
  stage: build
  script:
  - dotnet build
  artifacts:
    untracked: true

test:
  stage: test-pack
  script:
  - dotnet test

pack:
  stage: test-pack
  script:
  - dotnet pack --output "$(pwd)/dist/"
  artifacts:
    untracked: false
    paths:
    - ./dist/

deploy:
  stage: deploy
  script:
  - dotnet nuget push --api-key "${NUGET_API_KEY}" ./dist/*.nupkg
  only:
  - master
