image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

stages:
- build
- test-pack
- deploy

variables:
  CONFIGURATION: Release

build:
  stage: build
  script:
  - dotnet build
  cache: &cache_template
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - ./src/*/bin/*
    policy: push

test:
  stage: test-pack
  script:
  - dotnet test
  cache:
    <<: *cache_template
    policy: pull

pack:
  stage: test-pack
  script:
  - dotnet pack --output "$(pwd)/dist/"
  cache:
    <<: *cache_template
    policy: pull
  artifacts:
    paths:
    - ./dist/

deploy:
  stage: deploy
  script:
  - dotnet nuget push --api-key "${NUGET_API_KEY}" ./dist/*.nupkg
  only:
  - main
